### ISSUE TITLE
When will the blog be released?

### ISSUE THREAD

**Issue by pine** [ringo156/blog#1]
I'm very looking forward to see the blog 😄

**Comment by ringo156** [comment]
Please wait a moment now.
It is a blog view prototype.
![image](https://user-images.githubusercontent.com/9606695/92403940-741cdf80-f16d-11ea-8f89-ecc65b0ce1bc.png)

**Comment by pine** [comment]
Are you so busy? I cannot wait for a long time 😭

**Comment by ringo156** [comment]
fxxkin  die👎👎👎

**Comment by pine** [comment]
Are you serious? I trust you.

**Comment by ringo156** [comment]
I, I just deploy now😅

**Comment by pine** [comment]
How excellent!!
