### ISSUE TITLE
Do you have any trouble?

### ISSUE THREAD

**Issue by pine** [ringo156/blog#2]
Hello @ringo156, I'm waiting your new article for a long long time.

Do you have any trouble that I can help? I'm worried about your health.

**Comment by ringo156** [comment]
Hi @pine 
Thanks for worried about me.
I posted a new article, so I hope you will read it.
[web系素人がIT系企業に就職して勉強した本・動画・ブログまとめ](https://ringo156.github.io/blog/posts/new_graduate/)
Best regards!
